Multicountry2
ishti-du/RateMyProfessorPlus pull request #28
Opened 2021-11-12 17:14 UTC by mbc5954

- Request made whenever User will search any professor name
- Filters Professor name based on IP address country
- Filter Professor name globally

2021-11-14 19:02 UTC, bew5294 commented
Could you add the line `geoip2==4.4.0` to the `requirements.txt` file? This will make it easier for others to install the library you are using.

2021-11-14 19:11 UTC, bew5294 requested changes
I made a few comments about some changes I would like to see.

2021-11-15 14:53 UTC, mbc5954 commented on rmp_bd_app/templates/rmp_bd_app/base.html
> +             <input name="q" type="text" placeholder="Search..."><br> Search Globally
Thank you. Yes I added label.
and I didn't understand.. do you want me to change search bar instead of search box?
In CSS, I have both written search box and search bar.

2021-11-15 14:54 UTC, mbc5954 commented on rmp_bd_app/templates/rmp_bd_app/index.html
> +                 <input name="q" type="text" placeholder="Search...">
yes, I added in home page as well.

2021-11-17 17:11 UTC, kdgromova commented
please check my comments

2021-11-17 17:18 UTC, mbc5954 commented
- Request made whenever User will search any professor name
- Filters Professor name based on IP address country
- Filter Professor name globally

2021-11-17 17:18 UTC, merged